apiVersion: batch/v1
kind: CronJob
metadata:
  name: searchagent-freelancer
  labels:
    app: searchagent-freelancer

spec:
  timeZone: "Europe/Berlin"
  schedule: "12 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: searchagent-freelancer

        spec:
          imagePullSecrets:
            - name: registry-secret
          restartPolicy: OnFailure
          volumes:
            - name: searchagent-freelancer-volume
              persistentVolumeClaim:
                claimName: searchagent-freelancer-pvc
          containers:
            - image: eu-frankfurt-1.ocir.io/frs4lzee0jfi/searchagent_freelancer:latest
              name: searchagent-freelancer
              volumeMounts:
                - name: searchagent-freelancer-volume
                  mountPath: /data
              env:
                - name: SEARCH_TERM
                  valueFrom:
                    configMapKeyRef:
                      name: searchagent-freelancer-oracle
                      key: SEARCH_TERM
                - name: COLORIZE_TERMS
                  valueFrom:
                    configMapKeyRef:
                      name: searchagent-freelancer-oracle
                      key: COLORIZE_TERMS
                - name: ENABLE_GULP
                  valueFrom:
                    configMapKeyRef:
                      name: searchagent-freelancer-oracle
                      key: ENABLE_GULP
                - name: ENABLE_FREELANCE_DE
                  valueFrom:
                    configMapKeyRef:
                      name: searchagent-freelancer-oracle
                      key: ENABLE_FREELANCE_DE
                - name: ENABLE_FREELANCERMAP
                  valueFrom:
                    configMapKeyRef:
                      name: searchagent-freelancer-oracle
                      key: ENABLE_FREELANCERMAP
                - name: ENABLE_ETENGO
                  valueFrom:
                    configMapKeyRef:
                      name: searchagent-freelancer-oracle
                      key: ENABLE_ETENGO
                - name: ENABLE_HAYS
                  valueFrom:
                    configMapKeyRef:
                      name: searchagent-freelancer-oracle
                      key: ENABLE_HAYS

                - name: SMTP_HOST
                  valueFrom:
                    secretKeyRef:
                      name: searchagent-freelancer
                      key: SMTP_HOST
                - name: SMTP_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: searchagent-freelancer
                      key: SMTP_USERNAME
                - name: SMTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: searchagent-freelancer
                      key: SMTP_PASSWORD
                - name: SMTP_TO
                  valueFrom:
                    secretKeyRef:
                      name: searchagent-freelancer
                      key: SMTP_TO
                - name: SMTP_FROM
                  valueFrom:
                    secretKeyRef:
                      name: searchagent-freelancer
                      key: SMTP_FROM
